<<<<<<< HEAD
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
=======
import StyledComponentsRegistry from './registry';
import lingo, { Asset, ItemType, Kit } from '@lingo-app/node';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
>>>>>>> 7f48b21 (first commit for UI update)

export default function RootLayout({
  children,
}: {
<<<<<<< HEAD
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
=======
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </body>
    </html>
  );
>>>>>>> 7f48b21 (first commit for UI update)
}
